### ISSUE TITLE
添加 Run All 的总体进度条显示

### ISSUE THREAD

**Issue by Lindsaylin** [byzer-org/byzer-notebook-vue#120]

**Comment by Lindsaylin** [comment]
增加个 run all 的总体进度显示，比如横向的总体进度条。
![middle_img_v2_e48ad825-9029-4f1a-b978-d40e319e074g](https://user-images.githubusercontent.com/83326375/157417603-62314c05-8704-46e1-83a6-d6dfc8cb56ab.png)

**Comment by ZhengshuaiPENG** [comment]
2d
