### ISSUE TITLE
折叠显示的优化和一键展开/折叠功能

### ISSUE THREAD

**Issue by Lindsaylin** [byzer-org/byzer-notebook-vue#121]

**Comment by Lindsaylin** [comment]
目前的 cell 折叠过后，可获取信息不够全面，可以优化一下显示。且可以提供一个全局折叠的功能方便用户快速定位。
![middle_img_v2_663e1cc4-33c5-4e77-9bfd-511e38ddf9fg](https://user-images.githubusercontent.com/83326375/157418732-eac90c72-c2f2-4ed4-96a7-f0d54a95cdd9.png)

**Comment by ZhengshuaiPENG** [comment]
1d
