### ISSUE TITLE
调度实例的名称优化-失败节点改为笔记本名称

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-notebook-vue#196]
如图
![image](https://user-images.githubusercontent.com/11333496/178194651-a64bfe22-932b-4fb1-8e36-bb3b3ea43bc6.png)

当调度任务失败的时候，显示的是失败节点，这里期望用户能够通过错误的调度任务去修改对应的notebook，所以在提醒的时候应该显示 `笔记本名称/NotebookName`

**Comment by wangcheng15** [comment]
#### Test Case
1. 运行一个有错误的调度任务，设置的调度名称与 notebook 名称不一致
![image](https://user-images.githubusercontent.com/66863386/187657052-06709f99-e0e7-40d3-a2c4-790fe737394e.png)
![image](https://user-images.githubusercontent.com/66863386/187657290-8f4a486e-9ed7-41e0-a94b-5be2ec6271cd.png)

2. 查看调度实例中的报错信息，展示为 notebook 名称
![image](https://user-images.githubusercontent.com/66863386/187657381-d34651c8-5db5-40ab-9a31-f1d4952ab7c8.png)
